import = ["~/.config/alacritty/rose-pine.toml"]

live_config_reload = true

[shell]
program = "fish"
args = ["-l"]

[window]
startup_mode = 'Maximized'
padding = { x = 10, y = 10 }
decorations_theme_variant = "Dark"

[font]
normal = { family = "Dank Mono", style = "Regular" }
size = 13
