"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$character"""

[git_branch]
format = "[$branch(:$remote_branch)]($style) "

[git_status]
format = "([$all_status$ahead_behind]($style) )"
